pipeline {
  agent {
    dockerfile {
      dir 'docker'
      args '-e HOME=/tmp'
    }
  }

  stages {
    stage('Install dependencies') {
      steps {
        sh '/usr/bin/nuget restore ./src'
      }
    }

    stage('Build project') {
      steps {
        sh '/usr/bin/msbuild ./src \
              -p:Configuration=Release \
              -p:GamePath=/opt/stardew'
      }
    }
  }
}
