pipeline {
  agent {
    dockerfile {
      dir 'docker'
    }
  }

  stages {
    stage('Install dependencies') {
      steps {
        echo pwd()
        sh '/usr/bin/nuget restore'
      }
    }

    stage('Build project') {
      steps {
        sh '/usr/bin/msbuild -p:Configuration=Release'
      }
    }
  }
}
